/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PembukuanRouteImport } from './routes/pembukuan'
import { Route as ApiPosCloudRouteImport } from './routes/api/pos-cloud'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PembukuanRoute = PembukuanRouteImport.update({
  id: '/pembukuan',
  path: '/pembukuan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPosCloudRoute = ApiPosCloudRouteImport.update({
  id: '/api/pos-cloud',
  path: '/api/pos-cloud',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pembukuan': typeof PembukuanRoute
  '/api/pos-cloud': typeof ApiPosCloudRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pembukuan': typeof PembukuanRoute
  '/api/pos-cloud': typeof ApiPosCloudRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pembukuan': typeof PembukuanRoute
  '/api/pos-cloud': typeof ApiPosCloudRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pembukuan' | '/api/pos-cloud'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pembukuan' | '/api/pos-cloud'
  id: '__root__' | '/' | '/pembukuan' | '/api/pos-cloud'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PembukuanRoute: typeof PembukuanRoute
  ApiPosCloudRoute: typeof ApiPosCloudRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pembukuan': {
      id: '/pembukuan'
      path: '/pembukuan'
      fullPath: '/pembukuan'
      preLoaderRoute: typeof PembukuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pos-cloud': {
      id: '/api/pos-cloud'
      path: '/api/pos-cloud'
      fullPath: '/api/pos-cloud'
      preLoaderRoute: typeof ApiPosCloudRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PembukuanRoute: PembukuanRoute,
  ApiPosCloudRoute: ApiPosCloudRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
